services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: windmill
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8085:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin

  windmill:
    build: .
    platform: linux/amd64
    container_name: windmill
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - windmill_data:/data
    environment:
      DATABASE_URL: postgres://root:changeme@db:5432/windmill
      BASE_URL: http://localhost:8000
      RUST_LOG: info
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  windmill_data:
    driver: local
  vol-pgadmin_data:
    driver: local
  ny_taxi_postgres_data:
    driver: local
